export const produtos = [
  {
    imgCode: "2564",
    type: "piso",
    price: "7636",
    marca: "MARSET",
    description: "Nolita de chão",
  },
  {
    imgCode: "2566",
    type: "piso",
    price: "3500",
    marca: "?",
    description: "Luminária de piso",
  },
  {
    imgCode: "2569",
    type: "pendente",
    price: "13800",
    marca: "MARSET",
    description: "Olivia 45 cristal",
  },
  {
    imgCode: "2570",
    type: "pendente",
    price: "5600",
    marca: "MARSET",
    description: "Nolita (39)",
  },
  {
    imgCode: "2571",
    type: "pendente",
    price: "80",
    marca: "?",
    description: "Pendente prismático",
  },
  {
    imgCode: "2573",
    type: "pendente",
    price: "700",
    marca: "BERTOLUCCI",
    description: "Pendente urucum",
  },
  {
    imgCode: "2574",
    type: "pendente",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Pendente XL com disco",
  },
  {
    imgCode: "2575",
    type: "pendente",
    price: "450",
    marca: "BERTOLUCCI",
    description: "Pendente Gongue",
  },
  {
    imgCode: "2576",
    type: "pendente",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Pendente XL",
  },
  {
    imgCode: "2577",
    type: "pendente",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Pendente bolinha",
  },
  {
    imgCode: "2578",
    type: "pendente",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Pendente XL branco",
  },
  {
    imgCode: "2579",
    type: "pendente",
    price: "consultar",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2580",
    type: "pendente",
    price: "500",
    marca: "ILUMINAR",
    description: "Pendente",
  },
  {
    imgCode: "2581",
    type: "pendente",
    price: "500",
    marca: "ILUMINAR",
    description: "Pendente",
  },
  {
    imgCode: "2582",
    type: "pendente",
    price: "711",
    marca: "MODULAR",
    description: "Pendente Aton",
  },
  {
    imgCode: "2584",
    type: "pendente",
    price: "",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2585",
    type: "pendente",
    price: "3500",
    marca: "BERTOLUCCI",
    description: "Pendente Biombo",
  },
  {
    imgCode: "2586",
    type: "pendente",
    price: "7807",
    marca: "PRANDINA",
    description: "Pendente Guru S3",
  },
  {
    imgCode: "2587",
    type: "pendente",
    price: "7807",
    marca: "PRANDINA",
    description: "Pendente Guru S3",
  },
  {
    imgCode: "2588",
    type: "pendente",
    price: "consultar",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2589",
    type: "pendente",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Pendente XL",
  },
  {
    imgCode: "2590",
    type: "pendente",
    price: "5300",
    marca: "KUNDALINI",
    description: "Pendente Floob cristalo",
  },
  {
    imgCode: "2591",
    type: "pendente",
    price: "5300",
    marca: "KUNDALINI",
    description: "Pendente Floob cristalo",
  },
  {
    imgCode: "2592",
    type: "pendente",
    price: "2800",
    marca: "SECTO DESIGN",
    description: "Pendente Puncto 4203",
  },
  {
    imgCode: "2595",
    type: "pendente",
    price: "consultar",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2596",
    type: "pendente",
    price: "consultar",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2597",
    type: "pendente",
    price: "consultar",
    marca: "?",
    description: "Pendente",
  },
  {
    imgCode: "2598",
    type: "pendente",
    price: "5600",
    marca: "MARSET",
    description: "Pendente Nolita",
  },
  {
    imgCode: "2599",
    type: "pendente",
    price: "850",
    marca: "BERTOLUCCI",
    description: "Pendente Polca",
  },
  {
    imgCode: "2603",
    type: "pendente",
    price: "1200",
    marca: "BERTOLUCCI",
    description: "Pendente Pequim",
  },
  {
    imgCode: "2611",
    type: "pendente",
    price: "10484,22",
    marca: "PRANDINA",
    description: "Pendente Biluna S7",
  },
  {
    imgCode: "2612",
    type: "pendente",
    price: "10484,22",
    marca: "PRANDINA",
    description: "Pendente Biluna S7",
  },
  {
    imgCode: "2616",
    type: "pendente",
    price: "16035",
    marca: "PRANDINA",
    description: "Pendente Notte S9L Preto",
  },
  {
    imgCode: "2617",
    type: "pendente",
    price: "16035",
    marca: "PRANDINA",
    description: "Pendente Notte S9L Preto",
  },
  {
    imgCode: "2619",
    type: "pendente",
    price: "16035",
    marca: "PRANDINA",
    description: "Pendente Notte S9L Preto",
  },
  {
    imgCode: "2620",
    type: "pendente",
    price: "16035",
    marca: "PRANDINA",
    description: "Pendente Notte S9L Branco",
  },
  {
    imgCode: "2622",
    type: "arandela",
    price: "consultar",
    marca: "?",
    description: "Arandela",
  },
  {
    imgCode: "2623",
    type: "plafon",
    price: "2800",
    marca: "BERTOLUCCI",
    description: "Plafon Mube",
  },
  {
    imgCode: "2625",
    type: "plafon",
    price: "500",
    marca: "?",
    description: "Plafon",
  },
  {
    imgCode: "2627",
    type: "plafon",
    price: "2640",
    marca: "ILUMINAR",
    description: "Plafon Mambo",
  },
  {
    imgCode: "2628",
    type: "arandela",
    price: "consultar",
    marca: "?",
    description: "Arandela",
  },
  {
    imgCode: "2629",
    type: "arandela",
    price: "3373",
    marca: "MARSET",
    description: "Arandela Pop",
  },
  {
    imgCode: "2630",
    type: "plafon",
    price: "1200",
    marca: "ILUMINAR",
    description: "Plafon Piana",
  },
  {
    imgCode: "2631",
    type: "arandela",
    price: "consultar",
    marca: "?",
    description: "arandela ",
  },
  {
    imgCode: "2632",
    type: "arandela",
    price: "600",
    marca: "BERTOLUCCI",
    description: "Arandela Bionda",
  },
  {
    imgCode: "2633",
    type: "plafon",
    price: "2170",
    marca: "ILUMINAR",
    description: "Plafon ergo",
  },
  {
    imgCode: "2634",
    type: "mesa",
    price: "consultar",
    marca: "?",
    description: "Abajur",
  },
  {
    imgCode: "2635",
    type: "arandela",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Arandela",
  },
  {
    imgCode: "2636",
    type: "arandela",
    price: "900",
    marca: "INGO MAURER",
    description: "Arandela",
  },
  {
    imgCode: "2637",
    type: "arandela",
    price: "consultar",
    marca: "?",
    description: "Arandela",
  },
  {
    imgCode: "2638",
    type: "mesa",
    price: "consultar",
    marca: "ILUMINAR",
    description: "XL",
  },
  {
    imgCode: "2639",
    type: "arandela",
    price: "consultar",
    marca: "",
    description: "arandela",
  },
  {
    imgCode: "2640",
    type: "mesa",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Lampada de mesa",
  },
  {
    imgCode: "2641",
    type: "arandela",
    price: "consultar",
    marca: "ILUMINAR",
    description: "Arandela retangular Geo",
  },
  {
    imgCode: "2642",
    type: "arandela",
    price: "consultar",
    marca: "",
    description: "arandela",
  },
  {
    imgCode: "2645",
    type: "arandela",
    price: "consultar",
    marca: "ILUMINAR",
    description: "arandela",
  },
  {
    imgCode: "2646",
    type: "balizador",
    price: "consultar",
    marca: "",
    description: "Balizador",
  },
  {
    imgCode: "2647",
    type: "arandela",
    price: "consultar",
    marca: "",
    description: "Arandela",
  },
  {
    imgCode: "2648",
    type: "arandela",
    price: "consultar",
    marca: "",
    description: "Arandela",
  },
];
